name: PMD Check

on:
  pull_request:
    branches:
      - release/feb

jobs:
  pmd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run PMD
        uses: pmd/pmd-github-action@v2
        with:
          rulesets: 'config/ruleset.xml'
          sourcePath: 'force-app/main/default'
          analyzeModifiedFilesOnly: false
          createGitHubAnnotations: true
